[package]
name = "asp_gui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
asp_lib = { version = "0.1.5", path = "../asp_lib" }
eframe = "0.22.0"
egui = "0.22.0"
